name: test1

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Проверка репозитория
        uses: actions/checkout@v3
      - name: Настройка Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Установка Pipenv
        run: pip install pipenv
      - name: Установка зависимостей с помощью Pipenv
        run: pipenv install --dev
      - name: Запуск тестов
        run: |
          pipenv run pytest tests/
          pipenv run coverage report
