name: Test Workflow

on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Проверка репозитория
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Настройка Python
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Установка Pipenv
      - name: Install Pipenv
        run: pip install pipenv

      # Вывод содержимого Pipfile для отладки
      - name: Display Pipfile
        run: cat Pipfile

      # Установка зависимостей с помощью Pipenv
      - name: Install Dependencies
        run: |
          pipenv install --dev || { echo 'Pipenv install failed'; exit 1; }

      # Запуск тестов
      - name: Run Tests
        run: |
          pipenv run pytest tests/
          pipenv run coverage report
